version: "3"
services:
  localstack:
    image: localstack/localstack:1.2.0
    network_mode: bridge
    ports:
      - "4566:4566"  # LocalStack Edge Proxy
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
    volumes:
      - ./volume}:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
  redis:
    image: redis:6.2.6-bullseye
    network_mode: bridge
    ports: 
      - "6379:6379"