name: Functional tests

on:
    pull_request:

jobs:
    functional-tests:
        name: Run functional tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: docker-compose up -d
            - run: yarn
            - run: yarn test --ci
