name: Functional tests

on:
    pull_request:

jobs:
    functional-tests:
        name: Run functional tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  # Keep in sync with the plugin-server node version
                  node-version: '18.x'

            - run: docker-compose up -d

            - uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}

            - run: yarn

            - run: |
                  # Wait for LocalStack to be ready
                  until $(curl --output /dev/null --silent --head --fail http://localhost:4566); do
                      printf 'Waiting for LocalStack to be ready...'
                      sleep 1
                  done

                  yarn test

            - name: Upload code coverage results
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: coverage
                  path: coverage/
